# 04 · BPR

公式の前処理・探索範囲を保ち、29日／149日の別モデルを作ります。学習・調整・語彙を各期限内に限定し、CPUで順番に実行します。NDCGは原コードの分母の誤りを補正した標準DCG/IDCGを使います。

10試行、64因子、最終41/42/43の3シード。各シードを共通ヘッドで評価し、平均とシード間の差を補助分析で報告します。

In [1]:
import polars as pl
from IPython.display import display
from relisten import config
from relisten.official_models import build_official_features
from relisten.evaluation import evaluate_features

In [2]:
features = build_official_features("BPR")
display(features.select("model_end_day").group_by("model_end_day").len())

/Users/macuser/dev/paper1/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[I 2026-10-16 20:56:06,940] A new study created in RDB with name: BPR

[I 2026-10-16 20:56:06,943] A new study created in memory with name: no-name-19f8444f-4393-4c17-94d1-c67781ee88d8

BPR day29 trial0: 15.3s NDCG@100=0.00149

[I 2026-10-16 20:56:22,256] Trial 0 finished with value: 0.0014902811589265243 and parameters: {'iterations': 35, 'regularization': 0.5669849511478852, 'learning_rate': 0.008471801418819975}. Best is trial 0 with value: 0.0014902811589265243.

BPR day29 trial1: 26.7s NDCG@100=0.03191

[I 2026-10-16 20:56:48,943] Trial 1 finished with value: 0.031905983440471665 and parameters: {'iterations': 75, 'regularization': 6.0268891286825045e-05, 'learning_rate': 4.207053950287933e-05}. Best is trial 1 with value: 0.031905983440471665.

BPR day29 trial2: 7.8s NDCG@100=0.02096

[I 2026-10-16 20:56:56,783] Trial 2 finished with value: 0.020962840157476292 and parameters: {'iterations': 12, 'regularization': 0.21423021757741062, 'learning_rate': 0.002537815508265664}. Best is trial 1 with value: 0.031905983440471665.

BPR day29 trial3: 34.0s NDCG@100=0.07914

[I 2026-10-16 20:57:30,771] Trial 3 finished with value: 0.07913571213089803 and parameters: {'iterations': 110, 'regularization': 1.2674255898937214e-05, 'learning_rate': 0.07579479953347998}. Best is trial 3 with value: 0.07913571213089803.

BPR day29 trial4: 46.0s NDCG@100=0.03184

[I 2026-10-16 20:58:16,753] Trial 4 finished with value: 0.03183967960355115 and parameters: {'iterations': 168, 'regularization': 0.00011526449540315612, 'learning_rate': 5.3370327626039544e-05}. Best is trial 3 with value: 0.07913571213089803.

BPR day29 trial5: 7.9s NDCG@100=0.02619

[I 2026-10-16 20:58:24,700] Trial 5 finished with value: 0.026190989517088543 and parameters: {'iterations': 18, 'regularization': 0.00033205591037519585, 'learning_rate': 0.0012561043700013551}. Best is trial 3 with value: 0.07913571213089803.

BPR day29 trial6: 13.1s NDCG@100=0.03663

[I 2026-10-16 20:58:37,796] Trial 6 finished with value: 0.03663142659135235 and parameters: {'iterations': 42, 'regularization': 0.0002858549394196192, 'learning_rate': 0.0028016351587162596}. Best is trial 3 with value: 0.07913571213089803.

BPR day29 trial7: 6.5s NDCG@100=0.03083

[I 2026-10-16 20:58:44,295] Trial 7 finished with value: 0.03082918426885952 and parameters: {'iterations': 15, 'regularization': 0.000288883836236532, 'learning_rate': 0.0002920433847181409}. Best is trial 3 with value: 0.07913571213089803.

BPR day29 trial8: 13.0s NDCG@100=0.03130

[I 2026-10-16 20:58:57,339] Trial 8 finished with value: 0.031300368676593845 and parameters: {'iterations': 46, 'regularization': 0.08431013932082458, 'learning_rate': 6.290644294586152e-05}. Best is trial 3 with value: 0.07913571213089803.

BPR day29 trial9: 15.0s NDCG@100=0.03011

[I 2026-10-16 20:59:12,397] Trial 9 finished with value: 0.030111951826633922 and parameters: {'iterations': 56, 'regularization': 0.009163741808778781, 'learning_rate': 1.5339162591163613e-05}. Best is trial 3 with value: 0.07913571213089803.

[I 2026-10-16 21:00:31,421] A new study created in RDB with name: BPR

[I 2026-10-16 21:00:31,423] A new study created in memory with name: no-name-b7676600-90f2-4997-b83b-84ba2bca2084

BPR day149 trial0: 59.6s NDCG@100=0.01403

[I 2026-10-16 21:01:31,064] Trial 0 finished with value: 0.014027927748571641 and parameters: {'iterations': 35, 'regularization': 0.5669849511478852, 'learning_rate': 0.008471801418819975}. Best is trial 0 with value: 0.014027927748571641.

BPR day149 trial1: 109.1s NDCG@100=0.02885

[I 2026-10-16 21:03:20,167] Trial 1 finished with value: 0.028853433241695002 and parameters: {'iterations': 75, 'regularization': 6.0268891286825045e-05, 'learning_rate': 4.207053950287933e-05}. Best is trial 1 with value: 0.028853433241695002.

BPR day149 trial2: 23.2s NDCG@100=0.02728

[I 2026-10-16 21:03:43,398] Trial 2 finished with value: 0.027279865565443748 and parameters: {'iterations': 12, 'regularization': 0.21423021757741062, 'learning_rate': 0.002537815508265664}. Best is trial 1 with value: 0.028853433241695002.

BPR day149 trial3: 151.0s NDCG@100=0.05049

[I 2026-10-16 21:06:14,447] Trial 3 finished with value: 0.05049138679034043 and parameters: {'iterations': 110, 'regularization': 1.2674255898937214e-05, 'learning_rate': 0.07579479953347998}. Best is trial 3 with value: 0.05049138679034043.

BPR day149 trial4: 232.2s NDCG@100=0.02815

[I 2026-10-16 21:10:06,626] Trial 4 finished with value: 0.02814845646050145 and parameters: {'iterations': 168, 'regularization': 0.00011526449540315612, 'learning_rate': 5.3370327626039544e-05}. Best is trial 3 with value: 0.05049138679034043.

BPR day149 trial5: 29.4s NDCG@100=0.02760

[I 2026-10-16 21:10:36,013] Trial 5 finished with value: 0.027598854345943256 and parameters: {'iterations': 18, 'regularization': 0.00033205591037519585, 'learning_rate': 0.0012561043700013551}. Best is trial 3 with value: 0.05049138679034043.

BPR day149 trial6: 59.4s NDCG@100=0.05423

[I 2026-10-16 21:11:35,395] Trial 6 finished with value: 0.05423366575974451 and parameters: {'iterations': 42, 'regularization': 0.0002858549394196192, 'learning_rate': 0.0028016351587162596}. Best is trial 6 with value: 0.05423366575974451.

BPR day149 trial7: 27.8s NDCG@100=0.02861

[I 2026-10-16 21:12:03,159] Trial 7 finished with value: 0.02861132769026227 and parameters: {'iterations': 15, 'regularization': 0.000288883836236532, 'learning_rate': 0.0002920433847181409}. Best is trial 6 with value: 0.05423366575974451.

BPR day149 trial8: 64.4s NDCG@100=0.02875

[I 2026-10-16 21:13:07,536] Trial 8 finished with value: 0.02874800206559648 and parameters: {'iterations': 46, 'regularization': 0.08431013932082458, 'learning_rate': 6.290644294586152e-05}. Best is trial 6 with value: 0.05423366575974451.

BPR day149 trial9: 75.9s NDCG@100=0.02934

[I 2026-10-16 21:14:23,464] Trial 9 finished with value: 0.029336777771371517 and parameters: {'iterations': 56, 'regularization': 0.009163741808778781, 'learning_rate': 1.5339162591163613e-05}. Best is trial 6 with value: 0.05423366575974451.

shape: (2, 2)
┌───────────────┬─────────┐
│ model_end_day ┆ len     │
│ ---           ┆ ---     │
│ i32           ┆ u32     │
╞═══════════════╪═════════╡
│ 149           ┆ 3014337 │
│ 29            ┆ 1285567 │
└───────────────┴─────────┘

In [3]:
models = {f"BPR_seed{seed}":f"BPR_seed{seed}" for seed in (41,42,43)}
metrics = evaluate_features(features,models,"bpr_model_metrics.csv")
display(metrics.filter((pl.col("route")=="C") & (pl.col("split")=="test") & (pl.col("lower_days")==config.LOWER_BOUND_DAYS)))

evaluated L=1 T2 C

evaluated L=1 T2 B

evaluated L=1 T1 C

evaluated L=1 T1 B

evaluated L=3 T2 C

evaluated L=3 T2 B

evaluated L=3 T1 C

evaluated L=3 T1 B

evaluated L=7 T2 C

evaluated L=7 T2 B

evaluated L=7 T1 C

evaluated L=7 T1 B

evaluated L=14 T2 C

evaluated L=14 T2 B

evaluated L=14 T1 C

evaluated L=14 T1 B

shape: (14, 18)
┌──────────────┬──────────────────┬──────┬───────┬───┬────────────┬──────────┬──────────┬──────────┐
│ model        ┆ protocol         ┆ task ┆ route ┆ … ┆ global_auc ┆ pr_auc   ┆ log_loss ┆ brier    │
│ ---          ┆ ---              ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str              ┆ str  ┆ str   ┆   ┆ f64        ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪══════════════════╪══════╪═══════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ UserBaseline ┆ baseline         ┆ T2   ┆ C     ┆ … ┆ 0.607669   ┆ 0.135043 ┆ 0.31237  ┆ 0.086232 │
│ BPR_seed41   ┆ score_only       ┆ T2   ┆ C     ┆ … ┆ 0.538177   ┆ 0.10902  ┆ 0.316891 ┆ 0.08702  │
│ BPR_seed41   ┆ baseline_plus_sc ┆ T2   ┆ C     ┆ … ┆ 0.61243    ┆ 0.136899 ┆ 0.312466 ┆ 0.086246 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
│ BPR_seed42   ┆ score_only       ┆ T2   ┆ C     ┆ … ┆ 0.537851   ┆ 0.108974 ┆ 0.316929 ┆ 0.087027 │
│ BPR_seed42   ┆ baseline_plus_sc ┆ T2   ┆ C     ┆ … ┆ 0.612098   ┆ 0.136784 ┆ 0.312509 ┆ 0.086253 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
│ …            ┆ …                ┆ …    ┆ …     ┆ … ┆ …          ┆ …        ┆ …        ┆ …        │
│ BPR_seed41   ┆ baseline_plus_sc ┆ T1   ┆ C     ┆ … ┆ 0.61391    ┆ 0.263412 ┆ 0.484451 ┆ 0.154448 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
│ BPR_seed42   ┆ score_only       ┆ T1   ┆ C     ┆ … ┆ 0.52077    ┆ 0.20723  ┆ 0.490399 ┆ 0.155702 │
│ BPR_seed42   ┆ baseline_plus_sc ┆ T1   ┆ C     ┆ … ┆ 0.613859   ┆ 0.263389 ┆ 0.484437 ┆ 0.154438 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
│ BPR_seed43   ┆ score_only       ┆ T1   ┆ C     ┆ … ┆ 0.520835   ┆ 0.207276 ┆ 0.490428 ┆ 0.15571  │
│ BPR_seed43   ┆ baseline_plus_sc ┆ T1   ┆ C     ┆ … ┆ 0.613899   ┆ 0.263412 ┆ 0.484468 ┆ 0.154456 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
└──────────────┴──────────────────┴──────┴───────┴───┴────────────┴──────────┴──────────┴──────────┘

L=7・14を含む全感度分析も結果CSVに保存します。cold曲は最低スコアとし、独自の曲数削減・試行数削減は行いません。