# 04 · ItemKNN

公式の前処理・探索範囲を保ち、29日／149日の別モデルを作ります。学習・調整・語彙を各期限内に限定し、CPUで順番に実行します。NDCGは原コードの分母の誤りを補正した標準DCG/IDCGを使います。

ユーザー空間の公式ItemKNNをそのまま計算し、曲×曲の密行列は作りません。

In [1]:
import polars as pl
from IPython.display import display
from relisten import config
from relisten.official_models import build_official_features
from relisten.evaluation import evaluate_features

In [2]:
features = build_official_features("ItemKNN")
display(features.select("model_end_day").group_by("model_end_day").len())

ItemKNN day29 h=0 NDCG@100=0.13152

ItemKNN day29 h=0.001 NDCG@100=0.13154

ItemKNN day29 h=0.002 NDCG@100=0.13276

ItemKNN day29 h=0.004 NDCG@100=0.13528

ItemKNN day29 h=0.008 NDCG@100=0.13835

ItemKNN day29 h=0.016 NDCG@100=0.14255

ItemKNN day29 h=0.032 NDCG@100=0.14539

ItemKNN day29 h=0.064 NDCG@100=0.14775

ItemKNN day29 h=0.128 NDCG@100=0.14952

ItemKNN day29 h=0.256 NDCG@100=0.15106

ItemKNN day29 h=0.5 NDCG@100=0.15386

ItemKNN day29 h=1 NDCG@100=0.15663

ItemKNN day29 h=2 NDCG@100=0.15800

ItemKNN day149 h=0 NDCG@100=0.10642

ItemKNN day149 h=0.001 NDCG@100=0.10728

ItemKNN day149 h=0.002 NDCG@100=0.10791

ItemKNN day149 h=0.004 NDCG@100=0.10888

ItemKNN day149 h=0.008 NDCG@100=0.11084

ItemKNN day149 h=0.016 NDCG@100=0.11169

ItemKNN day149 h=0.032 NDCG@100=0.11219

ItemKNN day149 h=0.064 NDCG@100=0.11227

ItemKNN day149 h=0.128 NDCG@100=0.11248

ItemKNN day149 h=0.256 NDCG@100=0.11184

ItemKNN day149 h=0.5 NDCG@100=0.11054

ItemKNN day149 h=1 NDCG@100=0.10921

ItemKNN day149 h=2 NDCG@100=0.10704

shape: (2, 2)
┌───────────────┬─────────┐
│ model_end_day ┆ len     │
│ ---           ┆ ---     │
│ i32           ┆ u32     │
╞═══════════════╪═════════╡
│ 29            ┆ 1285567 │
│ 149           ┆ 3014337 │
└───────────────┴─────────┘

In [3]:
models = {"ItemKNN":"itemknn"}
metrics = evaluate_features(features,models,"itemknn_model_metrics.csv")
display(metrics.filter((pl.col("route")=="C") & (pl.col("split")=="test") & (pl.col("lower_days")==config.LOWER_BOUND_DAYS)))

evaluated L=1 T2 C

evaluated L=1 T2 B

evaluated L=1 T1 C

evaluated L=1 T1 B

evaluated L=3 T2 C

evaluated L=3 T2 B

evaluated L=3 T1 C

evaluated L=3 T1 B

evaluated L=7 T2 C

evaluated L=7 T2 B

evaluated L=7 T1 C

evaluated L=7 T1 B

evaluated L=14 T2 C

evaluated L=14 T2 B

evaluated L=14 T1 C

evaluated L=14 T1 B

shape: (6, 18)
┌──────────────┬──────────────────┬──────┬───────┬───┬────────────┬──────────┬──────────┬──────────┐
│ model        ┆ protocol         ┆ task ┆ route ┆ … ┆ global_auc ┆ pr_auc   ┆ log_loss ┆ brier    │
│ ---          ┆ ---              ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str              ┆ str  ┆ str   ┆   ┆ f64        ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪══════════════════╪══════╪═══════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ UserBaseline ┆ baseline         ┆ T2   ┆ C     ┆ … ┆ 0.607669   ┆ 0.135043 ┆ 0.31237  ┆ 0.086232 │
│ ItemKNN      ┆ score_only       ┆ T2   ┆ C     ┆ … ┆ 0.47139    ┆ 0.097904 ┆ 0.317393 ┆ 0.087121 │
│ ItemKNN      ┆ baseline_plus_sc ┆ T2   ┆ C     ┆ … ┆ 0.5989     ┆ 0.132748 ┆ 0.312862 ┆ 0.086349 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
│ UserBaseline ┆ baseline         ┆ T1   ┆ C     ┆ … ┆ 0.614387   ┆ 0.263604 ┆ 0.484497 ┆ 0.154408 │
│ ItemKNN      ┆ score_only       ┆ T1   ┆ C     ┆ … ┆ 0.539716   ┆ 0.223204 ┆ 0.489957 ┆ 0.155645 │
│ ItemKNN      ┆ baseline_plus_sc ┆ T1   ┆ C     ┆ … ┆ 0.614672   ┆ 0.27112  ┆ 0.484224 ┆ 0.154239 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
└──────────────┴──────────────────┴──────┴───────┴───┴────────────┴──────────┴──────────┴──────────┘

L=7・14を含む全感度分析も結果CSVに保存します。cold曲は最低スコアとし、独自の曲数削減・試行数削減は行いません。