# 04 · 公式SASRec

公式モデルとサンプラーはvendorに原文を保存しています。100epoch・batch256・64次元・2層2head・Adam0.001・dropout0・seed42を保ち、MPS（使えなければCPU）で29日／149日モデルを順に学習します。系列は公式同様、ユーザーごとの最後の200件です。

MPS非対応のnested tensor推論だけをwrapperで無効化します。2件未満の学習系列は次曲ペアが作れないため除外します。予測には起点以前の既知曲と条件を満たす今回の推薦だけを使います。

In [1]:
import polars as pl
from IPython.display import display
from relisten import config
from relisten.sequence_model import build_sasrec_features,device_name
from relisten.evaluation import evaluate_features
print("device:",device_name())

device: mps

In [2]:
features = build_sasrec_features()
display(features.select("model_end_day").group_by("model_end_day").len())

SASRec day29 epoch1/100: 4.1s loss=0.68610

SASRec day29 epoch2/100: 3.1s loss=0.61108

SASRec day29 epoch3/100: 3.2s loss=0.51352

SASRec day29 epoch4/100: 3.2s loss=0.44864

SASRec day29 epoch5/100: 3.1s loss=0.40849

SASRec day29 epoch6/100: 3.1s loss=0.38117

SASRec day29 epoch7/100: 3.4s loss=0.36178

SASRec day29 epoch8/100: 3.4s loss=0.34429

SASRec day29 epoch9/100: 3.4s loss=0.33014

SASRec day29 epoch10/100: 3.3s loss=0.31638

SASRec day29 epoch11/100: 3.3s loss=0.30510

SASRec day29 epoch12/100: 3.3s loss=0.29307

SASRec day29 epoch13/100: 3.3s loss=0.28281

SASRec day29 epoch14/100: 3.3s loss=0.27279

SASRec day29 epoch15/100: 3.3s loss=0.26321

SASRec day29 epoch16/100: 3.3s loss=0.25341

SASRec day29 epoch17/100: 3.5s loss=0.24424

SASRec day29 epoch18/100: 3.3s loss=0.23612

SASRec day29 epoch19/100: 3.3s loss=0.22751

SASRec day29 epoch20/100: 3.2s loss=0.21961

SASRec day29 epoch21/100: 3.0s loss=0.21224

SASRec day29 epoch22/100: 3.2s loss=0.20412

SASRec day29 epoch23/100: 3.0s loss=0.19741

SASRec day29 epoch24/100: 2.9s loss=0.19076

SASRec day29 epoch25/100: 2.9s loss=0.18483

SASRec day29 epoch26/100: 3.0s loss=0.17822

SASRec day29 epoch27/100: 3.0s loss=0.17197

SASRec day29 epoch28/100: 3.0s loss=0.16707

SASRec day29 epoch29/100: 2.9s loss=0.16124

SASRec day29 epoch30/100: 3.0s loss=0.15652

SASRec day29 epoch31/100: 3.0s loss=0.15134

SASRec day29 epoch32/100: 3.0s loss=0.14672

SASRec day29 epoch33/100: 3.0s loss=0.14261

SASRec day29 epoch34/100: 7.1s loss=0.13812

SASRec day29 epoch35/100: 8.3s loss=0.13396

SASRec day29 epoch36/100: 8.7s loss=0.13051

SASRec day29 epoch37/100: 7.9s loss=0.12627

SASRec day29 epoch38/100: 8.8s loss=0.12312

SASRec day29 epoch39/100: 8.7s loss=0.11993

SASRec day29 epoch40/100: 8.0s loss=0.11638

SASRec day29 epoch41/100: 9.4s loss=0.11300

SASRec day29 epoch42/100: 9.3s loss=0.11048

SASRec day29 epoch43/100: 9.0s loss=0.10745

SASRec day29 epoch44/100: 3.4s loss=0.10502

SASRec day29 epoch45/100: 3.3s loss=0.10186

SASRec day29 epoch46/100: 3.2s loss=0.09903

SASRec day29 epoch47/100: 3.1s loss=0.09730

SASRec day29 epoch48/100: 3.1s loss=0.09492

SASRec day29 epoch49/100: 3.1s loss=0.09264

SASRec day29 epoch50/100: 3.1s loss=0.09006

SASRec day29 epoch51/100: 3.1s loss=0.08825

SASRec day29 epoch52/100: 3.1s loss=0.08610

SASRec day29 epoch53/100: 3.1s loss=0.08438

SASRec day29 epoch54/100: 3.1s loss=0.08240

SASRec day29 epoch55/100: 3.1s loss=0.08102

SASRec day29 epoch56/100: 3.2s loss=0.07970

SASRec day29 epoch57/100: 3.1s loss=0.07717

SASRec day29 epoch58/100: 3.1s loss=0.07629

SASRec day29 epoch59/100: 3.1s loss=0.07418

SASRec day29 epoch60/100: 3.1s loss=0.07272

SASRec day29 epoch61/100: 3.1s loss=0.07140

SASRec day29 epoch62/100: 3.1s loss=0.06996

SASRec day29 epoch63/100: 3.1s loss=0.06866

SASRec day29 epoch64/100: 3.1s loss=0.06759

SASRec day29 epoch65/100: 3.1s loss=0.06589

SASRec day29 epoch66/100: 3.1s loss=0.06496

SASRec day29 epoch67/100: 3.1s loss=0.06344

SASRec day29 epoch68/100: 3.1s loss=0.06265

SASRec day29 epoch69/100: 3.1s loss=0.06174

SASRec day29 epoch70/100: 3.2s loss=0.06046

SASRec day29 epoch71/100: 3.1s loss=0.05929

SASRec day29 epoch72/100: 3.1s loss=0.05845

SASRec day29 epoch73/100: 3.1s loss=0.05754

SASRec day29 epoch74/100: 3.1s loss=0.05666

SASRec day29 epoch75/100: 3.1s loss=0.05557

SASRec day29 epoch76/100: 3.2s loss=0.05465

SASRec day29 epoch77/100: 3.2s loss=0.05390

SASRec day29 epoch78/100: 3.1s loss=0.05247

SASRec day29 epoch79/100: 3.1s loss=0.05206

SASRec day29 epoch80/100: 3.1s loss=0.05129

SASRec day29 epoch81/100: 3.1s loss=0.05031

SASRec day29 epoch82/100: 3.1s loss=0.04953

SASRec day29 epoch83/100: 3.1s loss=0.04900

SASRec day29 epoch84/100: 3.1s loss=0.04828

SASRec day29 epoch85/100: 3.1s loss=0.04758

SASRec day29 epoch86/100: 3.2s loss=0.04695

SASRec day29 epoch87/100: 3.2s loss=0.04610

SASRec day29 epoch88/100: 3.1s loss=0.04575

SASRec day29 epoch89/100: 3.1s loss=0.04472

SASRec day29 epoch90/100: 3.2s loss=0.04406

SASRec day29 epoch91/100: 3.2s loss=0.04394

SASRec day29 epoch92/100: 3.1s loss=0.04317

SASRec day29 epoch93/100: 3.1s loss=0.04255

SASRec day29 epoch94/100: 3.1s loss=0.04208

SASRec day29 epoch95/100: 3.1s loss=0.04161

SASRec day29 epoch96/100: 3.1s loss=0.04058

SASRec day29 epoch97/100: 3.1s loss=0.04011

SASRec day29 epoch98/100: 3.1s loss=0.03969

SASRec day29 epoch99/100: 3.1s loss=0.03955

SASRec day29 epoch100/100: 3.4s loss=0.03848

SASRec day149 epoch1/100: 5.0s loss=0.67052

SASRec day149 epoch2/100: 4.6s loss=0.53327

SASRec day149 epoch3/100: 4.7s loss=0.41581

SASRec day149 epoch4/100: 4.7s loss=0.35296

SASRec day149 epoch5/100: 5.0s loss=0.31630

SASRec day149 epoch6/100: 5.0s loss=0.29173

SASRec day149 epoch7/100: 5.5s loss=0.27349

SASRec day149 epoch8/100: 4.9s loss=0.25874

SASRec day149 epoch9/100: 4.8s loss=0.24586

SASRec day149 epoch10/100: 4.7s loss=0.23438

SASRec day149 epoch11/100: 4.7s loss=0.22403

SASRec day149 epoch12/100: 4.9s loss=0.21420

SASRec day149 epoch13/100: 4.9s loss=0.20503

SASRec day149 epoch14/100: 4.7s loss=0.19669

SASRec day149 epoch15/100: 5.0s loss=0.18888

SASRec day149 epoch16/100: 4.7s loss=0.18080

SASRec day149 epoch17/100: 4.7s loss=0.17358

SASRec day149 epoch18/100: 4.7s loss=0.16677

SASRec day149 epoch19/100: 4.7s loss=0.16047

SASRec day149 epoch20/100: 4.7s loss=0.15497

SASRec day149 epoch21/100: 4.8s loss=0.14858

SASRec day149 epoch22/100: 4.8s loss=0.14368

SASRec day149 epoch23/100: 4.6s loss=0.13799

SASRec day149 epoch24/100: 4.7s loss=0.13392

SASRec day149 epoch25/100: 4.7s loss=0.12905

SASRec day149 epoch26/100: 4.7s loss=0.12473

SASRec day149 epoch27/100: 4.7s loss=0.12043

SASRec day149 epoch28/100: 4.6s loss=0.11728

SASRec day149 epoch29/100: 4.6s loss=0.11363

SASRec day149 epoch30/100: 4.7s loss=0.10996

SASRec day149 epoch31/100: 4.8s loss=0.10654

SASRec day149 epoch32/100: 5.0s loss=0.10287

SASRec day149 epoch33/100: 4.7s loss=0.09993

SASRec day149 epoch34/100: 4.7s loss=0.09678

SASRec day149 epoch35/100: 4.7s loss=0.09406

SASRec day149 epoch36/100: 4.8s loss=0.09134

SASRec day149 epoch37/100: 4.6s loss=0.08866

SASRec day149 epoch38/100: 4.6s loss=0.08631

SASRec day149 epoch39/100: 4.7s loss=0.08386

SASRec day149 epoch40/100: 4.7s loss=0.08148

SASRec day149 epoch41/100: 4.8s loss=0.07961

SASRec day149 epoch42/100: 4.6s loss=0.07728

SASRec day149 epoch43/100: 4.6s loss=0.07514

SASRec day149 epoch44/100: 4.7s loss=0.07327

SASRec day149 epoch45/100: 4.7s loss=0.07128

SASRec day149 epoch46/100: 4.9s loss=0.06945

SASRec day149 epoch47/100: 4.9s loss=0.06772

SASRec day149 epoch48/100: 4.7s loss=0.06599

SASRec day149 epoch49/100: 4.6s loss=0.06431

SASRec day149 epoch50/100: 4.6s loss=0.06336

SASRec day149 epoch51/100: 4.6s loss=0.06173

SASRec day149 epoch52/100: 4.5s loss=0.06006

SASRec day149 epoch53/100: 4.5s loss=0.05894

SASRec day149 epoch54/100: 4.6s loss=0.05769

SASRec day149 epoch55/100: 4.7s loss=0.05622

SASRec day149 epoch56/100: 4.5s loss=0.05514

SASRec day149 epoch57/100: 4.8s loss=0.05397

SASRec day149 epoch58/100: 4.9s loss=0.05285

SASRec day149 epoch59/100: 4.5s loss=0.05195

SASRec day149 epoch60/100: 4.7s loss=0.05040

SASRec day149 epoch61/100: 4.5s loss=0.04979

SASRec day149 epoch62/100: 4.5s loss=0.04872

SASRec day149 epoch63/100: 4.5s loss=0.04775

SASRec day149 epoch64/100: 4.4s loss=0.04659

SASRec day149 epoch65/100: 4.5s loss=0.04578

SASRec day149 epoch66/100: 4.5s loss=0.04518

SASRec day149 epoch67/100: 4.5s loss=0.04437

SASRec day149 epoch68/100: 4.5s loss=0.04339

SASRec day149 epoch69/100: 4.5s loss=0.04265

SASRec day149 epoch70/100: 4.5s loss=0.04171

SASRec day149 epoch71/100: 4.5s loss=0.04120

SASRec day149 epoch72/100: 4.5s loss=0.04085

SASRec day149 epoch73/100: 4.5s loss=0.03962

SASRec day149 epoch74/100: 4.4s loss=0.03925

SASRec day149 epoch75/100: 4.4s loss=0.03835

SASRec day149 epoch76/100: 4.5s loss=0.03793

SASRec day149 epoch77/100: 4.5s loss=0.03730

SASRec day149 epoch78/100: 4.4s loss=0.03647

SASRec day149 epoch79/100: 4.5s loss=0.03608

SASRec day149 epoch80/100: 4.5s loss=0.03551

SASRec day149 epoch81/100: 4.5s loss=0.03478

SASRec day149 epoch82/100: 4.5s loss=0.03451

SASRec day149 epoch83/100: 4.5s loss=0.03383

SASRec day149 epoch84/100: 4.6s loss=0.03356

SASRec day149 epoch85/100: 4.4s loss=0.03299

SASRec day149 epoch86/100: 4.5s loss=0.03209

SASRec day149 epoch87/100: 4.5s loss=0.03186

SASRec day149 epoch88/100: 4.5s loss=0.03165

SASRec day149 epoch89/100: 4.5s loss=0.03119

SASRec day149 epoch90/100: 4.4s loss=0.03069

SASRec day149 epoch91/100: 4.6s loss=0.02994

SASRec day149 epoch92/100: 4.5s loss=0.02976

SASRec day149 epoch93/100: 4.5s loss=0.02950

SASRec day149 epoch94/100: 4.5s loss=0.02893

SASRec day149 epoch95/100: 4.5s loss=0.02868

SASRec day149 epoch96/100: 4.9s loss=0.02844

SASRec day149 epoch97/100: 4.7s loss=0.02811

SASRec day149 epoch98/100: 4.7s loss=0.02762

SASRec day149 epoch99/100: 4.7s loss=0.02727

SASRec day149 epoch100/100: 4.7s loss=0.02687

shape: (2, 2)
┌───────────────┬─────────┐
│ model_end_day ┆ len     │
│ ---           ┆ ---     │
│ i32           ┆ u32     │
╞═══════════════╪═════════╡
│ 29            ┆ 1285567 │
│ 149           ┆ 3014337 │
└───────────────┴─────────┘

In [3]:
metrics = evaluate_features(features,{"SASRec":"sasrec"},"sasrec_model_metrics.csv")
display(metrics.filter((pl.col("route")=="C") & (pl.col("split")=="test") & (pl.col("lower_days")==config.LOWER_BOUND_DAYS)))

evaluated L=1 T2 C

evaluated L=1 T2 B

evaluated L=1 T1 C

evaluated L=1 T1 B

evaluated L=3 T2 C

evaluated L=3 T2 B

evaluated L=3 T1 C

evaluated L=3 T1 B

evaluated L=7 T2 C

evaluated L=7 T2 B

evaluated L=7 T1 C

evaluated L=7 T1 B

evaluated L=14 T2 C

evaluated L=14 T2 B

evaluated L=14 T1 C

evaluated L=14 T1 B

shape: (6, 18)
┌──────────────┬──────────────────┬──────┬───────┬───┬────────────┬──────────┬──────────┬──────────┐
│ model        ┆ protocol         ┆ task ┆ route ┆ … ┆ global_auc ┆ pr_auc   ┆ log_loss ┆ brier    │
│ ---          ┆ ---              ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str              ┆ str  ┆ str   ┆   ┆ f64        ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪══════════════════╪══════╪═══════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ UserBaseline ┆ baseline         ┆ T2   ┆ C     ┆ … ┆ 0.607669   ┆ 0.135043 ┆ 0.31237  ┆ 0.086232 │
│ SASRec       ┆ score_only       ┆ T2   ┆ C     ┆ … ┆ 0.519614   ┆ 0.106193 ┆ 0.317167 ┆ 0.087065 │
│ SASRec       ┆ baseline_plus_sc ┆ T2   ┆ C     ┆ … ┆ 0.606905   ┆ 0.13495  ┆ 0.312525 ┆ 0.086261 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
│ UserBaseline ┆ baseline         ┆ T1   ┆ C     ┆ … ┆ 0.614387   ┆ 0.263604 ┆ 0.484497 ┆ 0.154408 │
│ SASRec       ┆ score_only       ┆ T1   ┆ C     ┆ … ┆ 0.483107   ┆ 0.188726 ┆ 0.490925 ┆ 0.155868 │
│ SASRec       ┆ baseline_plus_sc ┆ T1   ┆ C     ┆ … ┆ 0.613284   ┆ 0.262811 ┆ 0.484592 ┆ 0.154438 │
│              ┆ ore              ┆      ┆       ┆   ┆            ┆          ┆          ┆          │
└──────────────┴──────────────────┴──────┴───────┴───┴────────────┴──────────┴──────────┴──────────┘